import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { formatDateTime } from './formatDate';

export const exportCasesToPDF = (cases, title = 'Case Report') => {
  const doc = new jsPDF();

  doc.setFontSize(16);
  doc.text('SiteFlow', 14, 16);
  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(title, 14, 23);
  doc.text(`Generated: ${formatDateTime(new Date())}`, 14, 29);

  const rows = cases.map((c) => [
    c.caseNumber,
    c.siteName,
    c.siteAddress || '-',
    c.status.replace(/_/g, ' '),
    c.createdAt ? formatDateTime(c.createdAt) : '-',
    c.completedAt ? formatDateTime(c.completedAt) : '-',
  ]);

  autoTable(doc, {
    startY: 35,
    head: [['Case No.', 'Site Name', 'Address', 'Status', 'Created', 'Completed']],
    body: rows,
    styles: { fontSize: 8, cellPadding: 2 },
    headStyles: { fillColor: [139, 92, 246] }, // matches accent violet
    alternateRowStyles: { fillColor: [248, 248, 250] },
  });

  doc.save(`siteflow-cases-${Date.now()}.pdf`);
};

export const exportSingleCasePDF = (caseData, fields, department = 'STO') => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 14;
  let y = 15;

  // --- Header ---
  doc.setFillColor(20, 33, 61); // navy-ish header
  doc.rect(0, 0, pageWidth, 24, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont(undefined, 'bold');
  doc.text('BRICKNBATH', margin, 15);
  doc.setFontSize(8);
  doc.setFont(undefined, 'normal');
  doc.text('BATHROOM MEETS LIFESTYLE', margin, 20);

  doc.setFontSize(15);
  doc.setFont(undefined, 'bold');
  doc.text('CUSTOMER & SITE VISIT REPORT', pageWidth - margin, 12, { align: 'right' });
  doc.setFontSize(9);
  doc.setFont(undefined, 'normal');
  doc.text(`${department.toUpperCase()} SUBMITTED REPORT`, pageWidth - margin, 19, { align: 'right' });

  y = 32;
  doc.setTextColor(0, 0, 0);

  // --- Section 1: Case Details ---
  const sectionBar = (label) => {
    doc.setFillColor(20, 148, 132); // teal bar
    doc.rect(margin, y, pageWidth - margin * 2, 7, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(10);
    doc.setFont(undefined, 'bold');
    doc.text(label, margin + 2, y + 5);
    doc.setTextColor(0, 0, 0);
    y += 10;
  };

  sectionBar('CASE DETAILS');

  autoTable(doc, {
    startY: y,
    theme: 'grid',
    styles: { fontSize: 9, cellPadding: 3 },
    body: [
      ['Case Number', caseData.caseNumber, 'Status', caseData.status?.replace(/_/g, ' ')],
      ['Site Name', caseData.siteName, 'Site Address', caseData.siteAddress || '-'],
      ['Submitted By', caseData.stoForm?.submittedBy?.name || '-', 'Submitted On', formatDateTime(caseData.stoForm?.submittedAt)],
    ],
    columnStyles: {
      0: { fontStyle: 'bold', fillColor: [245, 245, 245], cellWidth: 35 },
      2: { fontStyle: 'bold', fillColor: [245, 245, 245], cellWidth: 35 },
    },
  });

  y = doc.lastAutoTable.finalY + 8;

  // --- Section 2: Visit Report (dynamic fields) ---
  sectionBar('VISIT REPORT DETAILS');

  const data = caseData.stoForm?.data || {};
  const labelMap = {};
  (fields || []).forEach((f) => { labelMap[f.fieldId] = f.label; });

  const rows = Object.entries(data).map(([key, value]) => [
    labelMap[key] || key,
    Array.isArray(value) ? value.join(', ') : String(value),
  ]);

  if (rows.length > 0) {
    autoTable(doc, {
      startY: y,
      theme: 'grid',
      styles: { fontSize: 9, cellPadding: 3 },
      columnStyles: {
        0: { fontStyle: 'bold', fillColor: [245, 245, 245], cellWidth: 55 },
      },
      body: rows,
    });
    y = doc.lastAutoTable.finalY + 8;
  } else {
    doc.setFontSize(9);
    doc.text('No visit report fields submitted.', margin, y + 5);
    y += 12;
  }

  // --- Section 3: Attachments ---
  const files = caseData.stoForm?.files || [];
  if (files.length > 0) {
    sectionBar('ATTACHMENTS');
    doc.setFontSize(8);
    files.forEach((f) => {
      doc.text(`• ${f.fileName}`, margin + 2, y + 4);
      y += 5;
    });
    y += 6;
  }

  // --- Footer: signature lines ---
  if (y > 250) { doc.addPage(); y = 20; }
  y += 10;
  doc.setDrawColor(150);
  doc.line(margin, y, margin + 60, y);
  doc.line(pageWidth - margin - 60, y, pageWidth - margin, y);
  doc.setFontSize(8);
  doc.text('Customer Signature / Date', margin, y + 5);
  doc.text('STO Signature / Date', pageWidth - margin - 60, y + 5);

  doc.setFontSize(7);
  doc.setTextColor(130);
  doc.text(
    `Generated by SiteFlow — ${formatDateTime(new Date())}`,
    margin,
    doc.internal.pageSize.getHeight() - 8
  );

  doc.save(`${caseData.caseNumber}-sto-report.pdf`);
};